name: Trigger auto deployment for zlhe-test-recommendation-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/zlhe-test-recommendation-service-AutoDeployTrigger-fdc57ac5-79de-4f62-9ccb-d49deb554653.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ZLHETESTRECOMMENDATIONSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ZLHETESTRECOMMENDATIONSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ZLHETESTRECOMMENDATIONSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.ZLHETESTRECOMMENDATIONSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ZLHETESTRECOMMENDATIONSERVICE_REGISTRY_PASSWORD }}
          containerAppName: zlhe-test-recommendation-service
          resourceGroup: zlhe-test
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


